version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2
executor: machine
jobs:
  build:
    machine:
      image: ubuntu-2004:202201-02
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: build
          command: ./gradlew assmeble jacocoTestReport --stacktrace --info
      - codecov/upload:
          file: build/reports/jacoco/test/*.xml
      - store_test_results:
          path: build/reports/tests/
      - store_artifacts:
          path: build/reports/tests/

workflows:
  build-workflow:
    jobs:
      - build
