version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
executor: machine
jobs:
  build:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: build
          command: ./gradlew jacocoTestReport --stacktrace --info
      - codecov/upload:
          file: build/reports/jacoco/test/*.xml

workflows:
  build-workflow:
    jobs:
      - build

