version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:

  build:
    machine:
      image: ubuntu-2004:202201-02

      environment:
        JVM_OPTS: -Xmx2G
        TERM: dumb

    steps:
      - checkout
      - run:
          name: build
          command: ./gradlew jacocoTestReport --stacktrace --info
      - codecov/upload:
          file: build/reports/jacoco/test/*.xml

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
